OS_DETECTION_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
CONSOLE_ENABLE = no

# scan rate approx ~1228 Hz
DEBOUNCE_TYPE = sym_eager_pk

BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no

DYNAMIC_MACRO_ENABLE = yes
MOUSE_ENABLE = yes
